cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
    - $HOME/.cargo/
    - target/

.cargo_test_template: &cargo_test
  script:
  - rustc --version && cargo --version
  - cargo build
  - cargo test --verbose --release

variables:
  RUST_BACKTRACE: "FULL"

before_script:
  - export PATH="/root/.cargo/bin:$PATH"

test:stable:
  image: "rustdocker/rust:stable"
  <<: *cargo_test

test:beta:
  image: "rustdocker/rust:beta"
  allow_failure: true
  <<: *cargo_test

test:nightly:
  image: "rustdocker/rust:nightly"
  allow_failure: true
  <<: *cargo_test

lint:clippy:
  image: "guangie88/rustfmt-clippy"
  allow_failure: true
  script:
    - cargo clippy
