name: check

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@V28
        with:
          github_access_token: ${{ github.token }}

      - uses: cachix/cachix-action@v15
        with:
          name: razielgn
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix flake check -L

      - run: nix build -L
